global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
  - job_name: nginx
    static_configs:
      - targets: ['localhost:9113']
  - job_name: nginx_stub
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /stub_status
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']